Fixes

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,9 +1,9 @@
 FROM ubuntu:noble
 
 RUN if id "ubuntu" &>/dev/null; then \
-        echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
+        echo "Deleting user 'ubuntu'" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \  
     else \
-        echo "User 'ubuntu' does not exist for $VARIANT"; \ 
+        echo "User 'ubuntu' does not exist"; \ 
     fi
 
 RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
@@ -37,7 +37,6 @@ RUN apt-get update \
     # This is the folder containing 'links' to benv and build script generator
     && apt-get update \
     && apt-get upgrade -y \
-    && add-apt-repository universe \
     && rm -rf /var/lib/apt/lists/*
 
 # Verify expected build and debug tools are present
@@ -50,16 +49,6 @@ RUN apt-get update \
                                                     libx11-xcb1 libcups2 libxcomposite1 libxdamage1 libxfixes3 libpango-1.0-0 libgbm1 libgtk-3-0 \
     # Clean up
     && apt-get autoremove -y && apt-get clean -y
-
-# Default to bash shell (other shells available at /usr/bin/fish and /usr/bin/zsh)
-ENV SHELL=/bin/bash \
-    DOCKER_BUILDKIT=1
-
-# Install and setup fish
-RUN apt-get install -yq fish \
-    && FISH_PROMPT="function fish_prompt\n    set_color green\n    echo -n (whoami)\n    set_color normal\n    echo -n \":\"\n    set_color blue\n    echo -n (pwd)\n    set_color normal\n    echo -n \"> \"\nend\n" \
-    && printf "$FISH_PROMPT" >> /etc/fish/functions/fish_prompt.fish \
-    && printf "if type code-insiders > /dev/null 2>&1; and not type code > /dev/null 2>&1\n  alias code=code-insiders\nend" >> /etc/fish/conf.d/code_alias.fish
 
 # Remove scripts now that we're done with them
 RUN apt-get clean -y && rm -rf /tmp/scripts
